spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  application:
    name: movies-app
  datasource:
    url: jdbc:mysql://nocng.id.vn:3307/movieweb?useSSL=false&serverTimezone=UTC
    username: root
    password: P@ssword*123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
server:
  port: 8080
api:
  prefix: /api/v1
